# Generated by Django 2.2 on 2021-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PK', 'Phụ kiện'), ('Q', 'Quần'), ('A', 'Áo')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondry'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
