# Generated by Django 2.2 on 2021-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210825_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Q', 'Quần'), ('A', 'Áo'), ('PK', 'Phụ kiện')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'secondry'), ('P', 'primary'), ('D', 'danger')], max_length=1),
        ),
    ]
