# Generated by Django 3.2.6 on 2021-08-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210825_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='get_avatar_full_path'),
        ),
    ]
